// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saxdxwouaiympkhowcia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNheGR4d291YWl5bXBraG93Y2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTkxODQsImV4cCI6MjA2NTQ3NTE4NH0.CBD6XEYgj-IOZICra4bUuV7X8xVUr5Q8rRliTMwnA3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);